# This file is used for convenience of local development.
# DO NOT STORE YOUR CREDENTIALS INTO GIT
export POSTGRES_USERNAME=postgres
export POSTGRES_PASSWORD=11311211
export POSTGRES_HOST=hacam308.cyy8kxlzkzig.us-east-1.rds.amazonaws.com
export POSTGRES_DB=postgres
export AWS_BUCKET=hacam308
export AWS_DEFAULT_REGION=us-east-1
export AWS_PROFILE=default
export JWT_SECRET=mysecretstring
export URL=http://localhost:8100
export AWS_ACCESS_KEY_ID=ASIARPOYBYFOGASCSKGU
export AWS_SECRET_ACCESS_KEY=FwEJkq5zT1CXUNXnlH14U2v68SOMixZpnBCBMAAz
export AWS_SESSION_TOKEN=FwoGZXIvYXdzEKf//////////wEaDJ8QScWW9tNMkiQUaSLVAcVmyL2cZU8/YLcsjrQpGsZ2eKX5snqDFjVQjTYQznj7DybGfdINm72p1NdA9vSundJRw/1N2huarvEE5GYIIfjjYRXMNRjlx+vzb/CcdPYudNIyJwcuhn51X2oQfUAvbkPRAALToCPTHFl4gXqPgTbZG5qWCLA4vyzjCQlepwIOUk1LlHah8yvla1iynPHo4xBmsj6s5Noz2g1IKaWZYBfKU1n4U332TVGZbmjUfy6r4imYaoVv60h0v8cYCG2UnhB8yicVGLLSE8GWgacgRHgUBB31jiiIwvmpBjItheyX3Vs8SScAdh+aOYHpAlcgQmG1j5QBUdqfFs1r/c+WqvJBMCyQ61cZ17Z2