branch-defaults:
  default:
    environment: haonc2
environment-defaults:
  haonc2:
    branch: null
    repository: null
global:
  application_name: udagram-api3
  default_ec2_keyname: vockey
  default_platform: Node.js 14 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: default
  sc: null
  workspace_type: Application
